import os
import uuid
from datetime import datetime
import boto3
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

class CertificateGenerator:
    def __init__(self):
        self.s3 = boto3.client(
            's3',
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            region_name=os.getenv("AWS_REGION", "ap-south-1")
        )
        self.bucket_name = os.getenv("AWS_S3_BUCKET_NAME", "foodbridge-certificates")

    def generate_safety_certificate(self, delivery_id: str, donation, restaurant, ngo) -> bytes:
        """
        Generates a PDF certificate using reportlab.
        """
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, height - 50, "FoodBridge AI - Food Safety Compliance Certificate")
        
        # Line separator
        c.setStrokeColor(colors.gray)
        c.line(50, height - 60, width - 50, height - 60)
        
        c.setFont("Helvetica", 12)
        
        # Restaurant Details
        c.drawString(50, height - 100, f"Restaurant Name: {restaurant.name if restaurant else 'Unknown'}")
        c.drawString(50, height - 120, f"FSSAI License No: {getattr(restaurant, 'fssai_license', 'N/A')}")
        
        # Donation Details
        c.drawString(50, height - 160, f"Food Type: {donation.food_type}")
        c.drawString(50, height - 180, f"Quantity: {donation.quantity}")
        c.drawString(50, height - 200, f"Prep Time: {donation.prep_time}")
        c.drawString(50, height - 220, f"Delivery Time: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC")
        
        # FSSAI Status
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 260, "FSSAI Compliance Status: ")
        c.setFillColor(colors.green)
        c.drawString(240, height - 260, "PASSED (✔)")
        c.setFillColor(colors.black)
        
        # NGO Details
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 300, f"Received by NGO: {ngo.name if ngo else 'Unknown'}")
        
        # Certificate ID
        cert_id = str(uuid.uuid4())
        c.setFont("Courier", 10)
        c.drawString(50, height - 340, f"Certificate ID: {cert_id}")
        c.drawString(50, height - 360, "[QR CODE TEXT REPRESENTATION]")
        
        # Footer
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(50, 50, f"Generated by FoodBridge AI on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC")
        
        c.showPage()
        c.save()
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    def upload_to_s3(self, pdf_bytes: bytes, delivery_id: str) -> str:
        """
        Uploads the PDF to S3 and returns the public URL.
        """
        object_name = f"certificates/{delivery_id}.pdf"
        
        # Check if dummy credentials or real
        if not os.getenv("AWS_ACCESS_KEY_ID"):
            # For local testing without AWS keys, just return a fake URL
            return f"https://{self.bucket_name}.s3.amazonaws.com/{object_name}"
            
        try:
            self.s3.put_object(
                Bucket=self.bucket_name,
                Key=object_name,
                Body=pdf_bytes,
                ContentType='application/pdf',
                ACL='public-read' # Note: adjust based on actual S3 permissions
            )
            url = f"https://{self.bucket_name}.s3.amazonaws.com/{object_name}"
            return url
        except Exception as e:
            import logging
            logging.error(f"Failed to upload certificate to S3: {e}")
            return f"s3-upload-failed-for-{delivery_id}"
